import 'package:flutter/material.dart';
import '../../services/database_service.dart';
import '../../models/trajet_model.dart';
import '../../models/agency_model.dart';

class AddTripScreen extends StatefulWidget {
  const AddTripScreen({super.key});

  @override
  State<AddTripScreen> createState() => _AddTripScreenState();
}

class _AddTripScreenState extends State<AddTripScreen> {
  final _db = DatabaseService();
  final _departureController = TextEditingController();
  final _destinationController = TextEditingController();
  final _priceController = TextEditingController();
  final _seatsController = TextEditingController();
  final _imageUrlController = TextEditingController();
  
  AgencyModel? _selectedAgency;
  DateTime _selectedDate = DateTime.now();

  void _saveTrip() async {
    if (_selectedAgency == null) return;

    final trajet = TrajetModel(
      id: '', // Will be generated by Firestore
      departure: _departureController.text.trim(),
      destination: _destinationController.text.trim(),
      departureTime: _selectedDate,
      price: double.tryParse(_priceController.text) ?? 0.0,
      totalSeats: int.tryParse(_seatsController.text) ?? 0,
      availableSeats: int.tryParse(_seatsController.text) ?? 0,
      agencyId: _selectedAgency!.id,
      agencyName: _selectedAgency!.name,
      busImageUrl: _imageUrlController.text.trim().isEmpty ? null : _imageUrlController.text.trim(),
    );

    try {
      await _db.createTrajet(trajet);
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Trajet créé avec succès")));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Erreur: ${e.toString()}")));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Ajouter un Trajet")),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            StreamBuilder<List<AgencyModel>>(
              stream: _db.agencies,
              builder: (context, snapshot) {
                if (!snapshot.hasData) return const CircularProgressIndicator();
                return DropdownButton<AgencyModel>(
                  hint: const Text("Sélectionner une agence"),
                  value: _selectedAgency,
                  isExpanded: true,
                  items: snapshot.data!.map((a) => DropdownMenuItem(value: a, child: Text(a.name))).toList(),
                  onChanged: (val) => setState(() => _selectedAgency = val),
                );
              },
            ),
            TextField(controller: _departureController, decoration: const InputDecoration(labelText: "Ville de départ")),
            TextField(controller: _destinationController, decoration: const InputDecoration(labelText: "Ville d'arrivée")),
            TextField(controller: _priceController, decoration: const InputDecoration(labelText: "Prix"), keyboardType: TextInputType.number),
            TextField(controller: _seatsController, decoration: const InputDecoration(labelText: "Nombre de places"), keyboardType: TextInputType.number),
            TextField(controller: _imageUrlController, decoration: const InputDecoration(labelText: "URL Image du bus (optionnel)")),
            const SizedBox(height: 20),
            ListTile(
              title: Text("Heure de départ: ${_selectedDate.toString()}"),
              trailing: const Icon(Icons.calendar_today),
              onTap: () async {
                final date = await showDatePicker(
                  context: context, 
                  initialDate: _selectedDate, 
                  firstDate: DateTime.now(), 
                  lastDate: DateTime.now().add(const Duration(days: 365))
                );
                if (date != null) setState(() => _selectedDate = date);
              },
            ),
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: _saveTrip,
              child: const Text("Enregistrer le trajet"),
            )
          ],
        ),
      ),
    );
  }
}
